name:                femtohs
version:             0.1.0.0
github:              "Ehtycs/femtohs"
license:             GPL-2
author:              "Antero Marjamäki"
maintainer:          "antero.marjamaki@gmail.com"
copyright:           "2019 Antero Marjamäki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/femtohs#readme>

dependencies:
- base >= 4.7 && < 5
- eigen == 3.3.7.0
- containers == 0.6.0.1
#extra-deps:
#- github: Ehtycs/haskell-gmsh
#  commit: 935b419bdc1ba5ee4ad44ec0674279da1f6dfe60


library:
  source-dirs: src

executables:
  femtohs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - femtohs

tests:
  femtohs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - femtohs
    - haskell-gmsh
